name: Deploy Web Dinamis to AWS

on:
  push:
    branches: [ main ]
    paths:
      - 'pertemuan12/web-dinamis/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web Dinamis
        uses: docker/build-push-action@v5
        with:
          context: ./pertemuan12/web-dinamis
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-dinamis-2388010014:latest